name: CI
on:
  push:
    branches:
    - master
  workflow_dispatch:

permissions: 
  contents: write 

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Depend
        run: |
          sudo apt install make autoconf automake libtool m4 wget gzip bzip2 bison g++ git cmake pkg-config re2c build-essential ca-certificates

      - name: Try Compile 
        run: |
          git clone https://github.com/LemonFan-maker/musl-cross-make.git
          cd musl-cross-make
          make
          cd ..

      - name: Make Tar
        run : |
          cd ${{ github.workspace }}/musl-cross-make
          rm -rf sources 
          cd ..
          tar -cvpzf musl-cross-make-aarch64.tgz musl-cross-make/ > /dev/null

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.sha }}
          name: aarch64-musl-linux-make-${{ github.sha }} 
          body: ${{ github.sha }}
          draft: false
          prerelease: false
          files: |
            ${{ github.workspace }}/musl-cross-make-aarch64.tgz
